### PR TITLE
Add BufferedCustomFileEmission

### PR DESCRIPTION
**Pull request by jackkoenig**
Uses virtual method .getBytesBuffered: Iterable[Array[Byte]] to optimize
file emission.

This is intended to enable faster annotation serialization. In particular this will be used to make `.fir` emission from Chisel support > 2 GiB `.fir` files. Currently. Chisel serializes the `.fir` to a `String` which has a max size of 2 GiB. We could use the `CustomFileEmission` API but it is 9-12x slower using just `Iterable[Byte]` so this PR is intended to make it much faster via buffering.

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [NA] Did you update the FIRRTL spec to include every new feature/behavior?
- [x] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

- performance improvement   
- new feature/API   

#### API Impact

Expands the API with a new subclass of `CustomFileEmission` called `BufferedCustomFileEmission`

#### Backend Code Generation Impact

No impact

#### Desired Merge Strategy

   - Squash

#### Release Notes

Introduce `BufferedCustomFileEmission` which enables Annotation writers to optimize serialization performance for their annotations.

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by jackkoenig** [comment]
I'm working on benchmarking serialization using this, will report back once I have numbers.

**Review by seldridge — APPROVED** [review]
Looks great!

**Comment by jackkoenig** [comment]
> I'm working on benchmarking serialization using this, will report back once I have numbers.

The numbers look great, completely erases the 9-12x slowdown and actually for the specific case of emitting `.fir` from Chisel3, it appears to make emission _faster_ over the Chisel 3 built-in emitter. See PR to follow in Chisel 3 using this new API.

**Comment by mwachs5** [comment]
Awesome!

**Pull request merged**
