### PR TITLE
ci: use official action to install oss cad tools

### PR DESCRIPTION
**Pull request by ekiwi**
#### Type of Improvement

- ci change

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Review by jackkoenig — APPROVED** [review]

**Comment by seldridge** [comment]
I'm seeing PR's failing on regressions after this went in. 🤔  Any idea what's going on?

E.g., https://github.com/chipsalliance/firrtl/runs/4193279276?check_suite_focus=true#step:3:8

**Comment by jackkoenig** [comment]
I have an upsteram PR coming that I think fixes the problem.

**Comment by jackkoenig** [comment]
See https://github.com/YosysHQ/setup-oss-cad-suite/pull/2

**Comment by ekiwi** [comment]
Thanks for fixing this, @jackkoenig !

**Pull request merged**
