### PR TITLE
[deprecation clean up] Remove firrtl.Driver.

### PR DESCRIPTION
**Pull request by sequencer**
depends on #2429
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you update the FIRRTL spec to include every new feature/behavior?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement
- code cleanup

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by sequencer** [comment]
Need fix tests.

**Comment by jackkoenig** [comment]
I want to merge this before releasing RC2, but I think it would be best if the removal of `Driver` from the tests were a separate commit from the removal of `Driver` from `main`. This is just in case it becomes an issue and users need us to revert it, it'll be much easier to just add back `Driver` to main. Would you mind making that change?

**Comment by sequencer** [comment]
I’ll split this commit to two today.

**Comment by sequencer** [comment]
done @jackkoenig

**Review by jackkoenig — APPROVED** [review]
Thanks @sequencer! For the record, I originally just meant two commits in this PR, the other PR wasn't strictly necessary but thank you!

**Pull request merged**
