### PR TITLE
This exposes the firrtl testing utils to repos that have a dependency on firrtl

### PR DESCRIPTION
**Pull request by chick**
These functions are in identically reproduced in chisel3 src/test/scala

### Contributor Checklist

- [x] Did you add Scaladoc to every public function/method?
- [NA] Did you update the FIRRTL spec to include every new feature/behavior?
- [x] Did you add at least one test demonstrating the PR?
- [NA] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [x] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement
- code refactoring
- code cleanup
This code has not been exposed and has been duplicated in chisel3's test directory

#### API Impact

Extends some portion of the test API to other chisel family repos.
No code change

#### Backend Code Generation Impact

No changes

#### Desired Merge Strategy

- Squash: The PR will be squashed and merged (choose this if you have no preference.

#### Release Notes

Provides a few nice tools for testing
methods
```
catchStatus
CatchWrites
grabStdOutErr
```
classes
```
ExceptOnExit
ExceptOnWrite
ExitException
WriteException
```

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by seldridge** [comment]
@chick: I added the `findCause` method in this PR by pushing directly. If that's a problem, I can back it out.

**Comment by davidbiancolin** [comment]
Will this not make it a little confusing re: what exists in the testutils package given that it's split across test and src?

**Comment by chick** [comment]
@davidbiancolin I think only in chisel3. Anywhere else there is no conflict because the test/ is not published. We should probably deprecate chisel3 or just make a PR and use the firrtl utils

**Comment by albert-magyar** [comment]
The approach here seems to be a little bit at odds with the one in #1412. I think we should ideally pick one way to export testing utilities to other projects, either in the default artifact or in an augmented test one.

**Comment by chick** [comment]
Not compelling

**Pull request closed without merging**
