### PR TITLE
Skip Formal CI checks via Github Actions not commit message

### PR DESCRIPTION
**Pull request by jackkoenig**
https://github.com/chipsalliance/firrtl/pull/2307 is failing due to awkwardness in the Formal CI checks. The old way of skipping them doesn't seem to be working so perhaps we should just do this using Labels anyway.

### Contributor Checklist

- [NA] Did you add Scaladoc to every public function/method?
- [NA] Did you update the FIRRTL spec to include every new feature/behavior?
- [ish] Did you add at least one test demonstrating the PR?
- [x] Did you delete any extraneous printlns/debugging code?
- [x] Did you specify the type of improvement?
- [x] Did you state the API impact?
- [x] Did you specify the code generation impact?
- [x] Did you request a desired merge strategy?
- [NA] Did you add text to be included in the Release Notes for this change?

#### Type of Improvement

  - CI enhancement

#### API Impact

No impact

#### Backend Code Generation Impact

No impact

#### Desired Merge Strategy

  - Squash (Definitely squash, I don't want to rebase because the commit history is the "test" of this PR)

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by jackkoenig** [comment]
The commit history here (that will squash away) shows that this works:
* fa71964 - Had [intentionally] incorrect logic to skip the formal checks on all non-push events (including PRs)
* 15f7f4d - Has correct logic and doesn't skip because this PR lacked the label at the time
* b288632 - With the label, the formal CI checks are correct skipped

**Comment by jackkoenig** [comment]
Marked for backporting to `1.4.x` so that we can get this fixed for https://github.com/chipsalliance/firrtl/pull/2307. 

IIRC, Mergify isn't allowed to open PRs that touch the `.github/workflows` directory so I'll probably have to manually backport.

**Review by seldridge — APPROVED** [review]
Nice!  Way better.

**Comment by jackkoenig** [comment]
One thing I don't love is that it's putting "Skipped" on `all_tests_passed`, so this may actually not actually work as is. I might have to move the skip into just the actual step inside `formal equivalence`. This would have the slightly negative consequence of having a green checkmark on `formal equivalence` even though it was skipped, but the label should make that obvious enough and we definitely want `all tests passed` to be green.

**Pull request merged**
