### PR TITLE
Add newline in the end of LoFIRRTL file

### PR DESCRIPTION
**Pull request by itviewer**
fix https://github.com/chipsalliance/firrtl/issues/2012

#### Type of Improvement

bug fix

#### API Impact
No
#### Backend Code Generation Impact
No

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Comment by ekiwi** [comment]
This looks great to me!

**Review by ekiwi — APPROVED** [review]
:ship:

**Comment by jackkoenig** [comment]
Should we backport this further to `1.2.x` and `1.3.x`?

**Comment by ekiwi** [comment]
> Should we backport this further to `1.2.x` and `1.3.x`?

This is using the new fast serializer that I added for `1.4` so I doubt it will cleanly apply to older versions. This might also be a regression introduced by my new serializer (haven't checked)

**Comment by jackkoenig** [comment]
Good point, if we need to do different fixes for other stable branches we can cross that bridge when we come to it.

**Pull request merged**
