### PR TITLE
[WIP] build.sc: fix NoSuchElementException: empty.head

### PR DESCRIPTION
**Pull request by vowstar**
### Contributor Checklist

- [ ] Did you add Scaladoc to every public function/method?
- [ ] Did you update the FIRRTL spec to include every new feature/behavior?
- [ ] Did you add at least one test demonstrating the PR?
- [ ] Did you delete any extraneous printlns/debugging code?
- [ ] Did you specify the type of improvement?
- [ ] Did you state the API impact?
- [ ] Did you specify the code generation impact?
- [ ] Did you request a desired merge strategy?
- [ ] Did you add text to be included in the Release Notes for this change?

#### Release Notes

- Use regular expressions to get version strings more rigorously
- Add version discriminant function, you can compare version size
- Correct the version comparison of antlr under special conditions
- Improve the version comparison of protoc

Closes: https://github.com/chipsalliance/firrtl/issues/2604

### Reviewer Checklist (only modified by reviewer)
- [ ] Did you add the appropriate labels?
- [ ] Did you mark the proper milestone (1.2.x, 1.3.0, 1.4.0) ?
- [ ] Did you review?
- [ ] Did you check whether all relevant Contributor checkboxes have been checked?
- [ ] Did you mark as `Please Merge`?

### CODE REVIEW

**Review by sequencer — APPROVED** [review]
LGTM, I'll merge this after CI passed. However SFC is going to be deprecated, there is another in source minimal SFC in the chisel repo. After chisel5 finally landing to master branch, this commit should be cherry-pick to chisel master.

**Comment by seldridge** [comment]
@vowstar: I pulled this commit into Chisel3 as part of the MFC migration here: https://github.com/chipsalliance/chisel3/pull/2982

Would you be able to also sign the CLA on the Chisel repository? Thanks!

**Comment by vowstar** [comment]
> @vowstar: I pulled this commit into Chisel3 as part of the MFC migration here: [chipsalliance/chisel3#2982](https://github.com/chipsalliance/chisel3/pull/2982)
> 
> Would you be able to also sign the CLA on the Chisel repository? Thanks!

Thanks for the reminder, I have signed the CLA on the Chisel repository

**Comment by seldridge** [comment]
Awesome. Thanks, again!

**Pull request merged**
